### ISSUE TITLE
Determine what info should be shown on dashboards

### ISSUE THREAD

**Issue by phredmund** [appl-domain-group-1/Bookkeeping-Buddy#151]

**Comment by Fidelia97** [comment]
**From Balance Sheet**
Assets - Cash, A/c receivable, Inventory
Liabilities - A/c payable, Short term borrowing

Current Ratio = Current assets ÷ Current liabilities (Normal range = 1 or better)

Working Capital = Inventory + A/c receivable (Normal range = 1.2 - 2.0)

Debt to Equity ratio = Total Liabilities ÷ Shareholder's Equity (Normal range = 2 - 2.5)

Debt Ratio = Total Liabilities ÷ Total Assets (Normal range = 0.5 or lower)

Equity Ratio = Total Equity ÷ Total Assets (Normal range = 0.5)
